import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useDashboard } from '../../context/DashboardContext';
import { Card } from '../../components/ui/Card';
import { EmptyState, SkeletonRows } from '../../components/ui/EmptyState';
import { StatusPill } from '../../components/ui/StatusPill';
import { Button } from '../../components/ui/Button';
import { RateVisitModal } from '../../components/dashboard/RateVisitModal';
import { BookingReceiptModal } from '../../components/booking/BookingReceiptModal';
import { classifyAppointments } from '../../utils/appointments';
import { toAppointmentDate } from '../../utils/format';
import { IconCalendar, IconGrid, IconPrinter, IconSparkle, IconStar } from '../../components/icons';

const TABS = [['upcoming', 'Upcoming'], ['recent', 'Recent'], ['history', 'History']];
function StarsRow({ rating }) { return <span className="flex items-center gap-0.5 text-gold-500" aria-label={`${rating} out of 5 stars`}>{Array.from({ length: 5 }).map((_, i) => <IconStar key={i} size={13} filled={i < rating} />)}</span>; }
function AppointmentRow({ appointment, onRate, onReceipt }) {
  const date = toAppointmentDate(appointment.raw_date, appointment.raw_time);
  const dateLabel = date.toLocaleDateString('en-PH', { timeZone: 'Asia/Manila', weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
  const timeLabel = date.toLocaleTimeString('en-PH', { timeZone: 'Asia/Manila', hour: 'numeric', minute: '2-digit', hour12: true });
  return <li className="grid gap-4 border-b border-line px-1 py-5 last:border-b-0 sm:grid-cols-[1.15fr_1fr_auto_auto] sm:items-center"><div className="flex min-w-0 items-center gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-line bg-blush-50 text-brand-300">{appointment.service_image ? <img src={appointment.service_image} alt="" loading="lazy" className="h-full w-full object-cover" /> : <IconSparkle size={17} aria-hidden="true" />}</div><div className="min-w-0"><p className="truncate font-display text-lg font-medium text-ink-900">{appointment.service}</p><p className="mt-1 text-xs text-ink-500">Reference {appointment.reference_no || appointment.id} · Booked {appointment.created_at ? new Date(appointment.created_at).toLocaleDateString('en-PH', { month: 'short', day: 'numeric' }) : '—'}</p></div></div><div className="text-sm"><p className="font-semibold text-ink-800">{dateLabel}</p><p className="mt-1 text-xs text-ink-500">{timeLabel}</p></div><div className="flex items-center gap-3"><StatusPill status={appointment.status} size="sm" />{appointment.has_rating ? <StarsRow rating={appointment.rating_given} /> : appointment.status === 'Completed' ? <button type="button" onClick={() => onRate(appointment.id)} className="text-xs font-bold text-blush-600 hover:text-blush-700"><IconStar size={13} filled /> Rate visit</button> : null}</div>{appointment.status === 'Completed' && <button type="button" onClick={() => onReceipt(appointment)} className="inline-flex min-h-10 items-center gap-1.5 text-xs font-bold text-brand-800 hover:text-brand-900"><IconPrinter size={14} />View / print receipt</button>}</li>;
}

export function MyAppointmentsPage() {
  const { appointments, customer, loading } = useDashboard();
  const [tab, setTab] = useState('upcoming'); const [rateFor, setRateFor] = useState(null); const [receiptFor, setReceiptFor] = useState(null);
  const groups = useMemo(() => classifyAppointments(appointments), [appointments]); const visible = groups[tab];
  return <div className="mx-auto max-w-[1240px]"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><h2 className="font-display text-3xl font-medium text-ink-900">My appointments</h2><p className="mt-2 text-sm text-ink-500">Keep track of upcoming requests and completed visits.</p></div><Link to="/dashboard/book"><Button>Book an appointment</Button></Link></div><div role="tablist" aria-label="Appointment groups" className="mb-5 flex flex-wrap gap-1 border-b border-line">{TABS.map(([key, label]) => <button key={key} type="button" role="tab" aria-selected={tab === key} onClick={() => setTab(key)} className={`min-h-11 border-b-2 px-4 text-sm font-bold transition-colors ${tab === key ? 'border-brand-800 text-brand-800' : 'border-transparent text-ink-500 hover:text-ink-900'}`}>{label}<span className="ml-2 text-xs text-ink-400">{loading ? '—' : groups[key].length}</span></button>)}</div><Card className="p-5 sm:p-7">{loading && <SkeletonRows rows={4} className="py-4" />}{!loading && !visible.length && <EmptyState icon={tab === 'upcoming' ? IconCalendar : tab === 'recent' ? IconSparkle : IconGrid} title={tab === 'upcoming' ? 'No upcoming appointments' : tab === 'recent' ? 'No recent visits' : 'Nothing in history yet'} description={tab === 'upcoming' ? 'Your next booking will appear here once it is placed.' : tab === 'recent' ? 'Completed visits from the last 30 days appear here.' : 'Older and cancelled bookings stay here for your records.'} action={<Link to="/dashboard/book" className="text-sm font-bold text-brand-800">Browse treatments</Link>} />}{!loading && visible.length > 0 && <ul>{visible.map((appointment) => <AppointmentRow key={appointment.id} appointment={appointment} onRate={setRateFor} onReceipt={setReceiptFor} />)}</ul>}</Card>{rateFor !== null && <RateVisitModal presetAppointmentId={String(rateFor)} onClose={() => setRateFor(null)} />}{receiptFor && <BookingReceiptModal receipt={{ reference: receiptFor.reference_no || receiptFor.id, customer, service: receiptFor.service, raw_date: receiptFor.raw_date, raw_time: receiptFor.raw_time, price: receiptFor.price, status: receiptFor.status, createdAt: receiptFor.created_at }} onClose={() => setReceiptFor(null)} />}</div>;
}
