-- Deliver new appointment requests independently to every active staff/admin
-- account. This is intentionally separate from customer notification history.

begin;

create table if not exists public.staff_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint staff_notifications_type_check check (type in ('new_booking')),
  constraint staff_notifications_recipient_appointment_type_key unique (recipient_id, appointment_id, type)
);

create index if not exists staff_notifications_recipient_created_idx
  on public.staff_notifications(recipient_id, created_at desc, id desc);

-- A browser may acknowledge a row, but cannot rewrite its ownership, source
-- appointment, type, content, or timestamp. Trusted service-role maintenance
-- remains able to repair data if an operator explicitly needs it.
create or replace function public.protect_staff_notification_fields()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if session_user not in ('postgres', 'supabase_admin')
     and coalesce(auth.role(), '') <> 'service_role'
     and (old.recipient_id is distinct from new.recipient_id
     or old.appointment_id is distinct from new.appointment_id
     or old.type is distinct from new.type
     or old.title is distinct from new.title
     or old.message is distinct from new.message
     or old.created_at is distinct from new.created_at) then
    raise exception 'Staff notification details are immutable';
  end if;
  return new;
end;
$$;

revoke all on function public.protect_staff_notification_fields() from public;
drop trigger if exists staff_notifications_protect_fields on public.staff_notifications;
create trigger staff_notifications_protect_fields before update on public.staff_notifications
for each row execute function public.protect_staff_notification_fields();

-- Appointment inserts performed by the legacy/import operator must not create
-- live alerts. Normal authenticated booking RPCs run as an authenticator
-- session and continue through this trigger; trusted service-role imports do
-- not represent a customer booking. No browser role can invoke the trigger
-- function directly.
create or replace function public.enqueue_staff_booking_notifications()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op <> 'INSERT'
     or session_user in ('postgres', 'supabase_admin')
     or coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  insert into public.staff_notifications(recipient_id, appointment_id, type, title, message)
  select p.id,
         new.id,
         'new_booking',
         'New appointment request',
         'New appointment request ' || new.reference_no || ' has been received.'
    from public.profiles p
   where p.role in ('staff', 'admin')
     and p.is_active = true
  on conflict (recipient_id, appointment_id, type) do nothing;

  return new;
end;
$$;

revoke all on function public.enqueue_staff_booking_notifications() from public;
drop trigger if exists appointments_enqueue_staff_notifications on public.appointments;
create trigger appointments_enqueue_staff_notifications after insert on public.appointments
for each row execute function public.enqueue_staff_booking_notifications();

alter table public.staff_notifications enable row level security;
revoke all on public.staff_notifications from public, anon, authenticated;
grant select, update (is_read) on public.staff_notifications to authenticated;
grant all on public.staff_notifications to service_role;
grant usage, select on sequence public.staff_notifications_id_seq to service_role;

drop policy if exists staff_notifications_recipient_read on public.staff_notifications;
create policy staff_notifications_recipient_read on public.staff_notifications
for select to authenticated
using (recipient_id = auth.uid() and public.is_staff());

drop policy if exists staff_notifications_recipient_update on public.staff_notifications;
create policy staff_notifications_recipient_update on public.staff_notifications
for update to authenticated
using (recipient_id = auth.uid() and public.is_staff())
with check (recipient_id = auth.uid() and public.is_staff());

-- Supabase projects normally create this publication. Keep local/test
-- databases that do not have it valid while making registration idempotent.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
         from pg_publication p
         join pg_publication_rel pr on pr.prpubid = p.oid
         join pg_class c on c.oid = pr.prrelid
         join pg_namespace n on n.oid = c.relnamespace
        where p.pubname = 'supabase_realtime'
          and n.nspname = 'public'
          and c.relname = 'staff_notifications'
     ) then
    execute 'alter publication supabase_realtime add table public.staff_notifications';
  end if;
end;
$$;

comment on table public.staff_notifications is 'Per-recipient realtime notifications for new customer appointment requests';

commit;
